name: Daily News Summary

on:
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch:

jobs:
  summarise:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install openai feedparser
      - name: Run summarise script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python .github/scripts/summarise.py
      - name: Commit summary
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add summaries/daily-summary.json
          git commit -m "Update daily summary"
          git push
